version: '3'

services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    env_file:
      - environment-development.env

  node:
    build: ./app/src
    user: node
    working_dir: /home/node/app
    env_file:
      - environment-development.env
    volumes:
      - ./app/src:/home/node/app
      - /home/node/app/node_modules
      - ./html:/home/node/app/html
    expose:
      - 3000
    ports:
      - 9229:9229
    command: npm run debug
    depends_on:
      - mongo
    links:
      - mongo

  nginx:
    build: ./nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    env_file:
      - environment-development.env
    ports:
      - 80:80
    depends_on:
      - node
    links:
      - node
